apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-store
  namespace: default
spec:
  replicas: 5
  selector:
    matchLabels:
      app: my-store
  template:
      metadata:
        labels:
          app: my-store
      spec:
        containers:
          - name: my-store-container
<<<<<<< HEAD
            image: abdulrehmanabid/jenkins-pipeline/
=======
            image: abdulrehmanabid/jenkins-pipeline:build-8
>>>>>>> 5f94dcedd099ca53b9ec075bd0d1a94cf5dd5bb3
            ports:
              - containerPort: 5000
              